version: "3.7"

services:
    athena:
        build:
            context: .
            dockerfile: Dockerfile
        command: flask run
        ports:
            - 5000:5000
        environment:
            - FLASK_APP=good/Athena.py
            - ENVIRONMENT=dev
